version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_project_b
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: nginx_project_b
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
